---
# tasks file for logout
- name: "DELTE WWN from Host Group"
  uri:
    url: "https://{{storage_ip}}/ConfigurationManager/v1/objects/host-wwns/{{wwn.portId}},{{wwn.hostGroupNumber}},{{wwn.hostWwn}}"
    method: DELETE
    body_format: json
    status_code: 202
    headers:
      Connection: "keep-alive"
      Authorization: "Session {{token_response.json.token}}"
      Content-Type: "application/json"
      Accept-Language: "en"
      Accept: "application/json, text/plain, */*"
      Sec-Fetch-Site: "same-origin"
      Sec-Fetch-Mode: "cors"
      Sec-Fetch-Dest: "empty"
    validate_certs: no
  register: new_job_task
