---
# tasks file for delete pool ID
- name: "Delete Pool ID"
  uri:
    url: "http://{{storage_ip}}/ConfigurationManager/simple/v1/objects/pools/{{pool_id}}"
    method: DELETE
    body_format: json
    status_code: 202
    headers:
      Connection: "keep-alive"
      Authorization: "Session {{token_response.json.token}}"
      Content-Type: "application/json"
      Accept-Language: "en"
      Accept: "application/json, text/plain, */*"
      Sec-Fetch-Site: "same-origin"
      Sec-Fetch-Mode: "cors"
    validate_certs: no
  register: new_job_task
  when: (pool_id is defined)

