---
# tasks file for logout
- name: "Get LUNS for Host Group and Number"
  uri:
    url: "https://{{storage_ip}}/ConfigurationManager/v1/objects/luns?portId={{lun.portId | urlencode}}&hostGroupNumber={{lun.hostGroupNumber | urlencode}}"
    method: GET
    headers:
      Connection: "keep-alive"
      Authorization: "Session {{token_response.json.token}}"
      Content-Type: "application/json"
      Accept-Language: "en"
      Accept: "application/json, text/plain, */*"
      Sec-Fetch-Site: "same-origin"
      Sec-Fetch-Mode: "cors"
    validate_certs: no
  register: luns

