---
# tasks file for logout
- name: "Discard Session Token"
  uri:
    url: "https://{{storage_ip}}/ConfigurationManager/v1/objects/sessions/{{token_response.json.sessionId}}"
    method: DELETE
    headers:
      Connection: "keep-alive"
      Authorization: "Session {{token_response.json.token}}"
      Content-Type: "application/json"
      Accept: "application/json, text/plain, */*"
      Sec-Fetch-Site: "same-origin"
      Sec-Fetch-Mode: "cors"
      Sec-Fetch-Dest: "empty"
    validate_certs: no
  register: logout_response
