---
# tasks file for Storage Information
- name: "Get Storage Information"
  uri:
    url: 'http://{{storage_ip}}/ConfigurationManager/simple/v1/objects/storage'
    method: GET
    headers:
      Accept: 'application/json, text/plain, */*'
      Accept-Language: en
      Authorization: "Session {{token_response.json.token}}"
      Connection: keep-alive
      Content-Type: application/json
    follow_redirects: safe
    validate_certs: no
  register: storage_data
