- name: Login, Create Pool and Logout of Storage Array
  hosts: localhost
  vars_files:
    - storage.json
  vars:
    - myauthstring: "{{storage_username}}:{{storage_password}}"

    - host_group_port: "CL1-A"
    - host_group_id: "1"

  tasks:
    - name: Login to Storage Array
      import_role:
        name: hv_login
      when: (token_response.json.token is undefined)

    - name: Get Host Groups
      import_role:
        name: hv_get_wwn
    - debug: var=host_wwns

    
