- name: Login and Logout of Storage Array
  hosts: localhost
  vars_files:
    - storage.json
  vars:
    - myauthstring: "{{storage_username}}:{{storage_password}}"
  tasks:
    - name: Logout of Storage Array
      import_role:
        name: hv_logout
