- name: Login, Create Pool and Logout of Storage Array
  hosts: localhost
  vars_files:
    - storage.json
  vars:
    - myauthstring: "{{storage_username}}:{{storage_password}}"
    - is_encrypted: false
    - pool_name: "Production"
    - raid_level: "RAID6" # Raid level to use. 
    - data_drive_count: 8 # Number of Drives to ADD.
    - drive_type_code: "SNB5B-R1R9NC" # where useOfTheDrive='free' from hv_get_drives role.
  tasks:
    - name: Login to Storage Array
      import_role:
        name: hv_login
      when: (token_response.json.token is undefined)

    - name: Display Drives available
      import_role:
        name: hv_get_drives

    - name: Display Available Drives
      ansible.builtin.debug:
        msg: "Drives Available: {{drive_data}}"

    - name: Create Pool
      import_role:
        name: hv_create_pool

    - name: Display Affected Resource
      ansible.builtin.debug:
        msg: "My Affected Resource: {{storage_ip}}{{new_job_task.json.statusResource}}"

    - name: Job Status
      import_role:
        name: hv_get_status_resource
    - debug: var=job_status_response

    - name: Sleep for 60 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 60
      delegate_to: localhost


    - name: "Set My Pool to use"
      set_fact:
        pool_id: "{{job_status_response.json.operationDetails[0].resourceId}}"


    - name: Delete Pool
      import_role:
        name: hv_delete_pool

    - name: Job Status
      import_role:
        name: hv_get_status_resource
    - debug: var=job_status_response

    
